//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABF2014Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FacturacaoAmbimedEntities : DbContext
    {
        public FacturacaoAmbimedEntities()
            : base("name=FacturacaoAmbimedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int CheckForErrorsPhase1(Nullable<System.Guid> token, Nullable<int> periodoFacturacaoID, ObjectParameter result)
        {
            var tokenParameter = token.HasValue ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(System.Guid));
    
            var periodoFacturacaoIDParameter = periodoFacturacaoID.HasValue ?
                new ObjectParameter("PeriodoFacturacaoID", periodoFacturacaoID) :
                new ObjectParameter("PeriodoFacturacaoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckForErrorsPhase1", tokenParameter, periodoFacturacaoIDParameter, result);
        }
    
        public virtual int FillContractTempTables(Nullable<System.Guid> token, Nullable<int> periodoFacturacaoID, ObjectParameter result)
        {
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            var periodoFacturacaoIDParameter = periodoFacturacaoID.HasValue ?
                new ObjectParameter("PeriodoFacturacaoID", periodoFacturacaoID) :
                new ObjectParameter("PeriodoFacturacaoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FillContractTempTables", tokenParameter, periodoFacturacaoIDParameter, result);
        }
    
        public virtual int FillCustomerTempTable(Nullable<System.Guid> token, ObjectParameter result)
        {
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FillCustomerTempTable", tokenParameter, result);
        }
    
        public virtual int FillCustomerUniverse(Nullable<System.Guid> token, Nullable<int> periodoFacturacao, string clientes, ObjectParameter result)
        {
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clientesParameter = clientes != null ?
                new ObjectParameter("Clientes", clientes) :
                new ObjectParameter("Clientes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FillCustomerUniverse", tokenParameter, periodoFacturacaoParameter, clientesParameter, result);
        }
    
        public virtual int FillRemainingTempTables(Nullable<System.Guid> tOKEN, Nullable<int> periodoFacturacao, ObjectParameter result)
        {
            var tOKENParameter = tOKEN.HasValue ?
                new ObjectParameter("TOKEN", tOKEN) :
                new ObjectParameter("TOKEN", typeof(System.Guid));
    
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FillRemainingTempTables", tOKENParameter, periodoFacturacaoParameter, result);
        }
    
        public virtual int GenerateExecutionToken(string requestedBy, ObjectParameter token)
        {
            var requestedByParameter = requestedBy != null ?
                new ObjectParameter("RequestedBy", requestedBy) :
                new ObjectParameter("RequestedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateExecutionToken", requestedByParameter, token);
        }
    
        public virtual int MRF_REGRA1(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> createdBySession, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA1", periodoFacturacaoParameter, clienteIDParameter, createdBySessionParameter, result);
        }
    
        public virtual int MRF_REGRA10(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA10", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA11(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> tOKEN, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tOKENParameter = tOKEN.HasValue ?
                new ObjectParameter("TOKEN", tOKEN) :
                new ObjectParameter("TOKEN", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA11", periodoFacturacaoParameter, clienteIDParameter, tOKENParameter, result);
        }
    
        public virtual int MRF_REGRA12(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> tOKEN, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tOKENParameter = tOKEN.HasValue ?
                new ObjectParameter("TOKEN", tOKEN) :
                new ObjectParameter("TOKEN", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA12", periodoFacturacaoParameter, clienteIDParameter, tOKENParameter, result);
        }
    
        public virtual int MRF_REGRA13(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA13", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA14(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA14", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA15(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA15", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA16(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA16", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA17(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA17", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA18(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA18", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA19(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA19", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA2(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> createdBySession, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA2", periodoFacturacaoParameter, clienteIDParameter, createdBySessionParameter, result);
        }
    
        public virtual int MRF_REGRA20(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> tOKEN, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tOKENParameter = tOKEN.HasValue ?
                new ObjectParameter("TOKEN", tOKEN) :
                new ObjectParameter("TOKEN", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA20", periodoFacturacaoParameter, clienteIDParameter, tOKENParameter, result);
        }
    
        public virtual int MRF_REGRA21(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA21", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA22(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA22", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA23(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> token, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA23", periodoFacturacaoParameter, clienteIDParameter, tokenParameter, result);
        }
    
        public virtual int MRF_REGRA3(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> createdBySession, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA3", periodoFacturacaoParameter, clienteIDParameter, createdBySessionParameter, result);
        }
    
        public virtual int MRF_REGRA4(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> createdBySession, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA4", periodoFacturacaoParameter, clienteIDParameter, createdBySessionParameter, result);
        }
    
        public virtual int MRF_REGRA5(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> createdBySession, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA5", periodoFacturacaoParameter, clienteIDParameter, createdBySessionParameter, result);
        }
    
        public virtual int MRF_REGRA6(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> createdBySession, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA6", periodoFacturacaoParameter, clienteIDParameter, createdBySessionParameter, result);
        }
    
        public virtual int MRF_REGRA7(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> createdBySession, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA7", periodoFacturacaoParameter, clienteIDParameter, createdBySessionParameter, result);
        }
    
        public virtual int MRF_REGRA8(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> createdBySession, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA8", periodoFacturacaoParameter, clienteIDParameter, createdBySessionParameter, result);
        }
    
        public virtual int MRF_REGRA9(Nullable<int> periodoFacturacao, string clienteID, Nullable<System.Guid> createdBySession, ObjectParameter result)
        {
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_REGRA9", periodoFacturacaoParameter, clienteIDParameter, createdBySessionParameter, result);
        }
    
        public virtual int MRF_SETUP_AUX_TABLES(string clienteID, Nullable<int> periodoFacturacao, Nullable<System.Guid> createdBySession)
        {
            var clienteIDParameter = clienteID != null ?
                new ObjectParameter("ClienteID", clienteID) :
                new ObjectParameter("ClienteID", typeof(string));
    
            var periodoFacturacaoParameter = periodoFacturacao.HasValue ?
                new ObjectParameter("PeriodoFacturacao", periodoFacturacao) :
                new ObjectParameter("PeriodoFacturacao", typeof(int));
    
            var createdBySessionParameter = createdBySession.HasValue ?
                new ObjectParameter("CreatedBySession", createdBySession) :
                new ObjectParameter("CreatedBySession", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MRF_SETUP_AUX_TABLES", clienteIDParameter, periodoFacturacaoParameter, createdBySessionParameter);
        }
    
        public virtual int CleanUpWorkerTables(Nullable<System.Guid> token)
        {
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CleanUpWorkerTables", tokenParameter);
        }
    }
}
